//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dagor.rc
//
#define IDS_UTIL_CAT                      1
#define IDS_FONTUTIL_NAME                 2
#define IDS_FONTUTIL_ROLL                 3
#define IDS_FONTDATA_FILES                4
#define IDS_SAVE_FONTDATA_TITLE           5
#define IDS_FILE_EXISTS                   6
#define IDS_FONTERR_HDNEBASE              7
#define IDS_FONTERR_NOHDIV                8
#define IDS_FONTERR_VDOUTU                9
#define IDS_FONTERR_VDOUTV                10
#define IDS_FILE_CREATE_ERR               11
#define IDS_FONTERR_VDEVEN                12
#define IDS_DAGORMAT                      13
#define IDS_AMB_COLOR                     14
#define IDS_DIFF_COLOR                    15
#define IDS_SPEC_COLOR                    16
#define IDS_EMIS_COLOR                    17
#define IDS_COLOR_CHANGE                  18
#define IDS_PARAM_CHANGE                  19
#define IDS_DAGORMAT_LONG                 20
#define IDS_EXPUTIL_NAME                  21
#define IDS_EXPUTIL_ROLL                  22
#define IDS_SCENE_FILES                   23
#define IDS_SAVE_SCENE_TITLE              24
#define IDS_FILE_WRITE_ERR                25
#define IDS_CHOOSE_DAGOR_PATH             26
#define IDS_NONE                          27
#define IDS_FILE_OPEN_ERR                 28
#define IDS_FILE_READ_ERR                 29
#define IDS_INVALID_DAGFILE               30
#define IDS_DAGIMP                        31
#define IDS_DAGIMP_LONG                   32
#define IDS_AUTHOR                        33
#define IDS_COPYRIGHT                     34
#define IDS_DAGIMP_SHORT                  35
#define IDS_DAGUTIL_NAME                  36
#define IDS_DAGUTIL_ROLL                  37
#define IDS_Dummy                         38
#define IDS_DUMMY_ROLL                    39
#define IDS_DAGOR_CAT                     40
#define IDS_WARNING                       41
#define IDS_EXPLOG_ROLL                   44
#define IDS_DAGORMAT2_LONG                46
#define IDS_DAGORPAR_TEXT_LONG            47
#define IDS_DAGORPAR_REAL_LONG            48
#define IDS_DAGORPAR_RANGE_LONG           49
#define IDS_DAGORPAR_ENUM_LONG            50
#define IDS_DAGORMAT2                     51
#define IDS_MatConvUtil_NAME              56
#define IDS_MatConvUtil_ROLL              57
#define IDS_RBHelper                      58
#define IDS_RBDUMMY_ROLL                  59
#define IDS_IMPUTIL_ROLL                  60
#define IDS_GET_NT_ERR                    61
#define IDS_PUT_NT_ERR                    62
#define IDS_NO_NTRK                       63
#define IDS_SEL_1_OBJ                     64
#define IDS_MUST_BE_EDMESH                65
#define IDS_LTMAP_ERR                     66
#define IDS_LTMAP_OK                      67
#define IDS_OBJS_RENDERED                 68
#define IDS_CANT_SAVE_BITMAP              69
#define IDS_NO_SEL                        70
#define IDS_FREECAM                       71
#define IDS_FREE_FORW                     72
#define IDS_FREE_BACKW                    73
#define IDS_FREE_LEFT                     74
#define IDS_FREE_RIGHT                    75
#define IDS_FREE_UP                       76
#define IDS_FREE_DOWN                     77
#define IDS_DAGFREECAM_UTIL_NAME          78
#define IDS_FREET_FORW                    79
#define IDS_FREET_BACKW                   80
#define IDS_FREET_LEFT                    81
#define IDS_FREET_RIGHT                   82
#define IDS_FREET_UP                      83
#define IDS_FREET_DOWN                    84
#define IDS_MAPOP_PERFORMED               85
#define IDS_MAPOP_NOTPERFORMED            86
#define IDS_MUST_BE_SPLINE                87
#define IDS_NO_SUCHSELSET                 88
#define IDS_DAGOR_EXPORT_IFACE            89
#define IDS_NOFACES_NODES                 90
#define IDS_POLYBUMPUTIL_NAME             91
#define IDS_SELECT_OUTPUT                 92
#define IDS_FILTER_TARGA                  93
#define IDS_FILTER_TARGA_DESC             94
#define IDS_FILTER_ALL                    95
#define IDS_FILTER_ALL_DESC               96
#define IDS_FILE_REPLACE                  97
#define IDS_SAVE_AS                       98
#define IDS_EMPTYSELECTION                99
#define IDS_INVALIDMAPCHANNEL             100
#define IDD_FONTUTIL                      101
#define IDS_CANCELLED                     101
#define IDD_DAGORMAT                      102
#define IDS_CANTCONVERT_HIGHPOLYNODE      102
#define IDD_EXPUTIL                       103
#define IDS_CANTCONVERT_LOWPOLYNODE       103
#define IDD_DAGUTIL                       104
#define IDS_INVALID_HIGHPOLYNODE          104
#define IDD_FREECAM                       105
#define IDS_INVALID_LOWPOLYNODE           105
#define IDD_DUMMY_PARAM                   106
#define IDR_FREECAM_ACC                   106
#define IDS_CANTWRITE_FILE                106
#define IDD_LOGROLL                       107
#define IDS_SUCCESS                       107
#define IDS_DEGENERATE_TRIANGLES          108
#define IDS_BIG_MESHES                    109
#define IDD_UV_UTILS                      109
#define IDD_POLYBUMP                      110
#define IDS_NON_DAGOR_MATERIALS           110
#define IDS_SUB_SUB_MATERIALS             111
#define IDD_DAGORMAT2_SHADER              111
#define IDD_DAGORPAR_NEW                  112
#define IDS_ABSOLUTE_PATHS                112
#define IDD_DAGORPAR_TEXT                 113
#define IDS_OBJECT_PROPERTIES_EDITOR_NAME 113
#define IDD_DAGORPAR_REAL                 114
#define IDS_PHYS_FILES                    114
#define IDS_SAVE_PHYS_TITLE               115
#define IDS_OPEN_SCENE_TITLE              116
#define IDD_DAGORPAR_BOOL                 116
#define IDD_DIALOG1                       117
#define IDS_IMPUTIL_PARAM_ROLL            117
#define IDD_MatConvUtil                   118
#define IDS_IMPUTIL_HELP_ROLL             118
#define IDD_OBJECT_PROPERTIES_EDITOR      119
#define IDS_EXPORT_TO_JSON                119
#define IDD_RBDUMMY_PARAM                 120
#define IDS_NON_DAGOR_LIGHTS              120
#define IDD_SCATTER                       121
#define IDD_SPLINES_AND_SMOOTH            122
#define IDD_MATERIALS                     123
#define IDD_OBJECT_PROPERTIES_FROM_BLK    124
#define IDD_MAX_GENERAL_ROLLUP            125
#define IDD_DAGOR_BRIGHTNESS              126
#define IDS_NO_SMOOTHING                  127
#define IDD_DAGORPAR_COLOR                128
#define IDS_DAGOR_IMPORT_IFACE            129
#define IDD_DAGOR_LOG_WINDOW              130
#define IDS_IMPUTIL_NAME                  130
#define IDD_IMPORT                        133
#define IDD_IMPUTIL_LEGACY                144
#define IDD_IMPUTIL_STANDARD              145
#define IDD_IMPUTIL                       148
#define IDD_IMPUTIL_WILDCARD              150
#define IDD_IMPUTIL_REGEX                 152
#define IDD_IMPUTIL_PARAM                 153
#define IDD_DIALOG5                       154
#define IDD_IMPUTIL_HELP                  155
#define IDD_EXPOTHER                      156
#define IDD_DAGORPAR_POINT2               162
#define IDD_DAGORPAR_POINT3               163
#define IDD_DAGORPAR_POINT4               164
#define IDD_DAGORMAT2_TEX                 165
#define IDD_DAGORMAT2_PARAM               166
#define IDD_DAGORMAT2_PHONG               167
#define IDD_DAGORPAR_POINT4_COLOR         168
#define IDD_DAGORPAR_GROUP                169
#define IDD_DAGORPAR_SHADER_SELECTOR      170
#define IDD_DAGORMAT2_PROXY               171
#define IDD_EXPORT_MAT_TO_JSON            172
#define OBJ_PROP_DLG_WIDTH                221
#define IDC_EXPORT                        1001
#define IDC_VSS_SAMPLE_STEP_SPIN          1001
#define IDC_2SIDED                        1002
#define IDC_SET_DAGORPATH                 1002
#define IDC_VSS_SAMPLE_SCALE_SPIN         1002
#define IDC_SCRIPT                        1003
#define IDC_SHOWALLMAPS                   1003
#define IDC_LIGHTMAP_SAMPLE_SIZE_SPIN     1003
#define IDC_ABLEND_VLTMAP                 1003
#define IDC_DAGORPATH                     1004
#define IDC_VISIBILITY_RANGE_SPIN         1004
#define IDC_ABLEND_LIGHTMAP               1004
#define IDC_EXPHIDDEN                     1005
#define IDC_STD2DAGMAT                    1005
#define IDC_FLARE_SIZE_SPIN               1005
#define IDC_CLSNAME                       1006
#define IDC_EXPSEL                        1006
#define IDC_FLARE_FAR_SIZE_SPIN           1006
#define IDC_GET_NTRK                      1007
#define IDC_FLARE_RANGE_SPIN              1007
#define IDC_EXPMESH                       1008
#define IDC_PUT_NTRK                      1008
#define IDC_FLARE_FAR_RANGE_SPIN          1008
#define IDC_EXPHELPER                     1009
#define IDC_HIDEMAPS                      1009
#define IDC_FLARE_Z_OFFSET_SPIN           1009
#define IDC_EXPLIGHT                      1010
#define IDC_FLARE_ANGLE_FROM_SPIN         1010
#define IDC_EDIT_BRIGHTNESS               1010
#define IDC_SIZE_S                        1011
#define IDC_EXPCAM                        1011
#define IDC_FLARE_ANGLE_TO_SPIN           1012
#define IDC_SIZ                           1018
#define IDC_LOGTEXT                       1020
#define IDC_EXPMATER                      1021
#define IDC_FREECAM_ON                    1022
#define IDC_MOVE_SPEED                    1023
#define IDC_TCSRC                         1023
#define IDC_EXPSPLINE                     1024
#define IDC_ROT_SPEED                     1024
#define IDC_TCDST                         1024
#define IDC_DAGMAT2STDMAT                 1024
#define IDC_TURBO                         1025
#define IDC_GRASSHT                       1025
#define IDC_TCMAPA                        1025
#define IDC_TCCOPY                        1026
#define IDC_MAX2MAT                       1026
#define IDC_TCSWAP                        1027
#define IDC_CONVERT_SPACES                1027
#define IDC_TCMOVE                        1028
#define IDC_IMPORT_MS_ANIM                1028
#define IDC_GRASSTILE                     1029
#define IDC_APPLYSELECTEDFACES            1029
#define IDC_GRASSSEGS                     1030
#define IDC_FID                           1030
#define IDC_MAKEGRASS                     1031
#define IDC_TCKILL                        1031
#define IDC_GRASSUP                       1032
#define IDC_TCINFO                        1032
#define IDC_GRASSUSETANG                  1033
#define IDC_EXPORT_PHYS                   1033
#define IDC_PROJSPL                       1034
#define IDC_CALC_MOMJ                     1034
#define IDC_PJS_MAXSEGLEN                 1035
#define IDC_CALC_MOMJ_ON_EXPORT           1035
#define IDC_PJS_OPTANGLE                  1036
#define IDC_PJS_OPTSEGLEN                 1037
#define IDC_GRASSGRAVITY                  1038
#define IDC_GRASSSTEPS                    1039
#define IDC_TCXCHG                        1040
#define IDC_SMOOTHSEL                     1040
#define IDC_TCFLIPV                       1041
#define IDC_MESHSMOOTH                    1041
#define IDC_TCFLIPU                       1042
#define IDC_TM_DIVIDEDIR                  1042
#define IDC_TCUK                          1043
#define IDC_USE_SMOOTH                    1043
#define IDC_TCVK                          1044
#define IDC_SHARPNESS                     1044
#define IDC_TCMUL                         1045
#define IDC_SMTHITERATIONS                1045
#define IDC_TCUO                          1046
#define IDC_AROUND                        1046
#define IDC_TCVO                          1047
#define IDC_SELSET                        1047
#define IDC_TCADD                         1048
#define IDC_GENOBJSURF                    1048
#define IDC_OBJNUM                        1049
#define IDC_SELFACE                       1049
#define IDC_OBJGENSEED                    1050
#define IDC_SELVERT                       1050
#define IDC_AMB                           1051
#define IDC_GS_SLOPE                      1051
#define IDC_DIFF                          1052
#define IDC_GS_SET2NORM                   1052
#define IDC_SPEC                          1053
#define IDC_GS_USESMGR                    1053
#define IDC_EMIS                          1054
#define IDC_GS_ROTATEZ                    1054
#define IDC_TCCOPYBUF                     1054
#define IDC_SHIN                          1055
#define IDC_GS_SELFACES                   1055
#define IDC_START                         1055
#define IDC_SHIN_S                        1056
#define IDC_GS_SCALEXYS                   1056
#define IDC_TCPASTEBUF                    1056
#define IDC_HIGHPOLY                      1056
#define IDC_CLASSNAME                     1057
#define IDC_GS_SCALEXY                    1057
#define IDC_LOWPOLY                       1057
#define IDC_GS_SCALEZ                     1058
#define IDC_GS_SCALEXYE                   1060
#define IDC_WIDTH                         1061
#define IDC_GS_SCALEZS                    1062
#define IDC_HEIGHT                        1062
#define IDC_GS_SCALEZE                    1063
#define IDC_EXPAND                        1063
#define IDC_SPACE                         1064
#define IDC_MAPCHANNEL                    1065
#define IDC_HIGHPOLYNAME                  1066
#define IDC_LOWPOLYNAME                   1067
#define IDC_FDIST_PERCENT                 1069
#define IDC_LATEST                        1071
#define IDC_BDIST_PERCENT                 1072
#define IDC_BACK_WEIGHT                   1074
#define IDC_FDIST_CM                      1075
#define IDC_BDIST_CM                      1076
#define IDC_OUTPUTPATH                    1077
#define IDC_SET_OUTPUTPATH                1078
#define IDC_SELFACES                      1079
#define IDC_PARAM_NEW                     1089
#define IDC_PARAM_NAME                    1091
#define IDC_PAR_TEXT_VALUE                1096
#define IDC_PAR_COLOR_VALUE               1115
#define IDC_PARAM_DELETE                  1116
#define IDC_CONVERT                       1118
#define IDC_COLLAPSE                      1119
#define IDC_CONVERT_NEW                   1120
#define IDC_ENUMERATE                     1121
#define IDC_SIMPLE_VLTMAP                 1122
#define IDC_AUTO                          1123
#define IDC_WORLD_NORMAL_X                1126
#define IDC_WORLD_NORMAL_Y                1127
#define IDC_WORLD_NORMAL_Z                1128
#define IDC_LOCAL_NORMAL_X                1129
#define IDC_LOCAL_NORMAL_Y                1130
#define IDC_LOCAL_NORMAL_Z                1131
#define IDC_FORCE_VSS                     1132
#define IDC_VSS_SAMPLE_STEP               1133
#define IDC_VSS_SAMPLE_SCALE              1134
#define IDC_LIGHTMAP_SAMPLE_SIZE          1135
#define IDC_VISIBILITY_RANGE              1136
#define IDC_SELF_SHADOWING                1137
#define IDC_FLARE_ANGLE_FROM              1138
#define IDC_FLARE_ANGLE_TO                1139
#define IDC_FLARE_SIZE                    1140
#define IDC_FLARE_FAR_SIZE                1141
#define IDC_FLARE_FAR_RANGE               1142
#define IDC_FLARE_RANGE                   1143
#define IDC_FLARE_COLOR_R                 1145
#define IDC_IDC_WORLD_NORMAL_DIFF         1146
#define IDC_LOCAL_NORMAL_DIFF             1147
#define IDC_FORCE_VSS_DIFF                1148
#define IDC_VSS_SAMPLE_STEP_DIFF          1149
#define IDC_VSS_SAMPLE_SCALE_DIFF         1150
#define IDC_LIGHTMAP_SAMPLE_SIZE_DIFF     1151
#define IDC_VISIBILITY_RANGE_DIFF         1152
#define IDC_SELF_SHADOWING_DIFF           1153
#define IDC_FLARE_ANGLE_DIFF              1154
#define IDC_FLARE_SIZE_DIFF               1155
#define IDC_FLARE_FAR_SIZE_DIFF           1156
#define IDC_FLARE_RANGE_DIFF              1157
#define IDC_FLARE_FAR_RANGE_DIFF          1158
#define IDC_PHYSICAL_MATERIAL_DIFF        1159
#define IDC_FLARE_COLOR_G                 1160
#define IDC_FLARE_COLOR_B                 1161
#define IDC_FLARE_COLOR_DIFF              1162
#define IDC_FLARE_Z_OFFSET                1163
#define IDC_FLARE_Z_OFFSET_DIFF           1164
#define IDC_PHYSICAL_MATERIAL             1166
#define IDC_FLARE_COLOR                   1167
#define IDC_ROLLUPWINDOW                  1167
#define IDC_REMOVE_DEGENERATES            1168
#define IDC_ATEST                         1169
#define IDS_SCATTER_ROLL                  1170
#define IDS_SPLINES_AND_SMOOTH_ROLL       1171
#define IDS_MATERIALS_ROLL                1172
#define IDC_CALC                          1172
#define IDS_UV_UTILS_ROLL                 1173
#define IDC_CUSTOM                        1173
#define IDC_SIMPLE_LIGHTMAP               1202
#define IDC_SELECT_FLOOR                  1203
#define IDC_EXPORT_INSTANCES              1204
#define IDC_EXP_VNORM                     1205
#define IDC_EXPMATEROPT                   1206
#define IDC_OPEN_LOG                      1207
#define IDC_CLEAR_LOG                     1208
#define IDC_EXPORT_MODE                   1209
#define IDC_USE_LEGACY_IMPORT             1210
#define IDC_IMPORT_LOD                    1211
#define IDC_IMPORT_DP                     1213
#define IDC_IMPORT_DMG                    1214
#define IDC_IMPORT_DESTR                  1215
#define IDC_IMPORT_DM                     1216
#define IDC_REPLACE_EXISTING_LAYER        1217
#define IDC_RENAME_NEW_LAYER              1218
#define IDC_STATIC1                       1218
#define IDC_STATIC2                       1219
#define IDC_STATIC3                       1220
#define IDC_STATIC4                       1221
#define IDC_STATIC8                       1222
#define IDC_TAB1                          1225
#define IDC_IMPORT                        1227
#define IDC_SEPARATE_LAYERS               1233
#define IDC_OPENDIR                       1234
#define IDC_OPEN_DOC                      1234
#define IDC_PARAM_DELETE_ALL              1234
#define IDC_RESOLVE_HIER                  1234
#define IDC_PATHLIST_INCL                 1239
#define IDC_REIMPORT_EXISTING             1240
#define IDC_PATHLIST_EXCL                 1241
#define IDC_GROUP_INCL                    1242
#define IDC_GROUP_EXCL                    1243
#define IDC_PATHLIST_ADD_INCL             1244
#define IDC_PATHLIST_DEL_INCL             1245
#define IDC_PATHLIST_ADD_EXCL             1246
#define IDC_PATHLIST_DEL_EXCL             1247
#define IDC_SEARCH_IN_SUBFOLDERS          1248
#define IDC_ENUM_2SIDED                   1251
#define IDC_PARAM_START                   1252
#define IDC_PAR_BOOL_VALUE                1253
#define IDC_PAR_POINT_VALUE_0             1255
#define IDC_PAR_POINT_VALUE_SPINNER_0     1256
#define IDC_BACKFACE_1                    1257
#define IDC_SHADER_CLASS_LIST             1257
#define IDC_BACKFACE_2                    1258
#define IDC_BACKFACE_REAL2                1259
#define IDC_PROXY_EXPORT                  1259
#define IDC_PAR_POINT_VALUE_1             1261
#define IDC_PAR_POINT_VALUE_SPINNER_1     1262
#define IDC_PARAM_NAME_EDIT               1262
#define IDC_PAR_POINT_VALUE_2             1263
#define IDC_PROXY_IMPORT                  1263
#define IDC_PAR_POINT_VALUE_SPINNER_2     1264
#define IDC_ASSET_PREFIX                  1264
#define IDC_PAR_POINT_VALUE_3             1265
#define IDC_RESOLVE_NAMES                 1265
#define IDC_PAR_POINT_VALUE_SPINNER_3     1266
#define IDC_REMOVE_SKIN_MOD               1266
#define IDC_TEX0                          2000
#define IDC_TEX1                          2001
#define IDS_DAGEXP_LONG                   2001
#define IDC_TEX2                          2002
#define IDS_DAGEXP_SHORT                  2002
#define IDC_TEX3                          2003
#define IDS_DAGEXP                        2003
#define IDC_TEX4                          2004
#define IDS_DAGORPAR_COLOR_LONG           2004
#define IDC_TEX5                          2005
#define IDC_TEX6                          2006
#define IDC_TEX7                          2007
#define IDC_TEX8                          2008
#define IDC_TEX9                          2009
#define IDC_TEX10                         2010
#define IDC_TEX11                         2011
#define IDC_TEX12                         2012
#define IDC_TEX13                         2013
#define IDC_TEX14                         2014
#define IDC_TEX15                         2015
#define IDR_FREE_FORW                     40001
#define IDR_FREE_BACKW                    40002
#define IDR_FREE_RIGHT                    40003
#define IDR_FREE                          40004
#define IDR_FREE_LEFT                     40005
#define IDR_FREE_UP                       40006
#define IDR_FREE_DOWN                     40007
#define IDR_FREET_LEFT                    40008
#define IDR_FREET_RIGHT                   40009
#define IDR_FREET_FORW                    40010
#define IDR_FREET_BACKW                   40011
#define IDR_FREET_UP                      40012
#define IDR_FREET_DOWN                    40013

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE 158
#define _APS_NEXT_COMMAND_VALUE  40014
#define _APS_NEXT_CONTROL_VALUE  1267
#define _APS_NEXT_SYMED_VALUE    101
#endif
#endif
