#ifndef LIGHTS_PARTITION_INCLUDED
#define LIGHTS_PARTITION_INCLUDED 1

#include "renderLightsConsts.hlsli"

#define OMNI_LIGHT_BOUND_SPHERE_RADIUS_SCALE 1.1f

#define CLUSTERED_OMNI_LIGHTS_COUNT_INDEX 0
#define FAR_OMNI_LIGHTS_COUNT_INDEX 2
#define CLUSTERED_SPOT_LIGHTS_COUNT_INDEX 4
#define FAR_SPOT_LIGHTS_COUNT_INDEX 6
#define LIGHTS_COUNTS_BUF_RECORDS_COUNT 8

#define CLUSTERED_OMNI_LIGHTS_IDS_OFFSET 0
#define FAR_OMNI_LIGHTS_IDS_OFFSET MAX_SCENE_OMNI_LIGHTS
#define CLUSTERED_SPOT_LIGHTS_IDS_OFFSET (2 * MAX_SCENE_OMNI_LIGHTS)
#define FAR_SPOT_LIGHTS_IDS_OFFSET (2 * MAX_SCENE_OMNI_LIGHTS + MAX_SCENE_SPOT_LIGHTS)
#define LIGHTS_DATA_BUF_RECORDS_COUNT (2 * MAX_SCENE_OMNI_LIGHTS + 2 * MAX_SCENE_SPOT_LIGHTS)

#endif
