#ifndef RENDER_LIGHTS_CONSTS_INCLUDED
#define RENDER_LIGHTS_CONSTS_INCLUDED

#define TEX_ID_MULTIPLIER (1 << 5)

#define MAX_CLUSTERED_SPOT_LIGHTS 256
#define MAX_CLUSTERED_OMNI_LIGHTS 256

#define MAX_SCENE_OMNI_LIGHTS 2048
#define MAX_SCENE_SPOT_LIGHTS 2048

#ifndef M_PI
#define M_PI 3.1415926536
#endif

#define IES_TEX_ID_TYPE_BIT_OFFSET 1
#define IES_TEX_ID_TYPE_BIT_MASK 1 // 0b1
#define IES_TEX_ID_TYPE__IES 0 // 0b0
#define IES_TEX_ID_TYPE__PROJ 1 // 0b1

#define USE_OCTAHEDRAL_MAPPING 1

#define SPOT_LIGHT_ROLL_BIT_OFFSET 2
#define SPOT_LIGHT_ROLL_BIT_COUNT 11
#define SPOT_LIGHT_ROLL_MAX_VALUE ((1<<SPOT_LIGHT_ROLL_BIT_COUNT) - 1)
#define SPOT_LIGHT_ROLL_MASK (SPOT_LIGHT_ROLL_MAX_VALUE << SPOT_LIGHT_ROLL_BIT_OFFSET)

#define SPOT_LIGHT_CONTACT_SHADOW_MASK (0x03)

#define SPOT_LIGHT_ID_BIT_OFFSET 13
#define SPOT_LIGHT_ID_BIT_COUNT 11
#define SPOT_LIGHT_ID_MASK (((1 << SPOT_LIGHT_ID_BIT_COUNT) - 1) << SPOT_LIGHT_ID_BIT_OFFSET)
#define SPOT_LIGHT_SOURCE_RADIUS_BIT_OFFSET 24
#define LIGHT_SOURCE_RADIUS_BIT_COUNT 8
#define LIGHT_SOURCE_RADIUS_MASK ((1 << LIGHT_SOURCE_RADIUS_BIT_COUNT) - 1)
#define LIGHT_SOURCE_RADIUS_MAX_CM LIGHT_SOURCE_RADIUS_MASK
#define LIGHT_SOURCE_RADIUS_CM_PER_M 100

#define OMNI_LIGHT_ID_MASK 0xFFFF
#define OMNI_LIGHT_SOURCE_RADIUS_BIT_OFFSET 16

#define OMNI_LIGHT_FLAG_MUZZLE_FLASH 1

#endif